name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        cache: true

    - name: Install libvips
      run: |
        sudo apt-get update
        sudo apt-get install -y libvips-dev

    - name: Install dependencies
      run: |
        go mod download
        go mod tidy

    - name: Install golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest
        skip-pkg-cache: true
        skip-build-cache: true

    - name: Run linting
      run: golangci-lint run ./...

    - name: Run tests with coverage
      run: |
        go test -race -coverprofile=coverage.out -covermode=atomic ./...
        go tool cover -func=coverage.out

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.out
        fail_ci_if_error: false

    - name: Build application
      run: go build -v -o bin/server ./cmd/server

    - name: Archive build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: server-binary
        path: bin/server
